app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

'''
POST 클래스 추가, MEDIA_URL 연결

MEDIA_ROOT는 실제 파일이 업로드되는 기준 경로
MEDIA_URL은 사용자가 업로드한 파일을 제공할 URL
config.urls에 추가한 static()은 MEDIA_URL로의 request에 대해
MEDIA_ROOT에서 찾은 파일을 response로 돌려줌

'''


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', views.index),
    path('members/', include('members.urls')),
    # path('media/<str:path>/',특정view_function추가),
    # 위 기능을 요약한 장고기능이 있음 - 하단 + static
] + static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path
from members import views

app_name = 'members'

urlpatterns = [
    # localhost:8000/posts
    path('login/', views.login_view, name='members-login'),
    path('logout/',views.logout_view, name='members-logout')
]

app/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

# config.urls
# path('posts/', include(이 urlpatterns)) 이하 경로를 만들면 됨

urlpatterns = [
    # localhost:8000/posts
    path('', views.post_list, name='post-list'),

    # localhost:8000/posts/1
    path('<int:pk>', views.post_detail, name='post-detail'),
]

app/members/models.py
from django.db import models

app/posts/models.py
from django.conf import settings
from django.db import models

'''
POST 클래스 추가, MEDIA_URL 연결

MEDIA_ROOT는 실제 파일이 업로드되는 기준 경로
MEDIA_URL은 사용자가 업로드한 파일을 제공할 URL
config.urls에 추가한 static()은 MEDIA_URL로의 request에 대해
MEDIA_ROOT에서 찾은 파일을 response로 돌려줌

'''

class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    photo = models.ImageField(
        upload_to='post',
        blank=True,
    )
    content = models.TextField(blank=True)
    created_at = models.DateField(auto_now_add=True)


# admin에 등록
# superuser생성
# 로그인해서 post 하나 추가하기

app/config/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect


def index(request):
    # 방법 1
    # return HttpResponseRedirect ('/posts/')

    # 방법 2
    return redirect('posts:post-list')

app/members/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect


def login_view(request):
    # 1. member.urls <- 'members/'로 include 되도록 config.urls 모듈에 추가
    # 2. path 구현 (URL:'/members/login/')
    # 3. path와 이 view 연결
    # 4. 잘 나오는지 먼저 확인
    # 5. 잘 나오면 form을 작성 (username, password를 받는 input 2개)
    # templates/members/login.html

    # 6.form 작성 후에는 POST 방식 요청을 보내서이 뷰에서 request.POST에 요청이 잘 왔는지 확인
    # 7. 일단은 받은 username, passwords 값을 HttpResponse에 보여주도록 한다.
    # username = request.POST['username']
    # passwords = request.POST['password']
    # return HttpResponse('login_view')
    # print(request.POST)
    # runserver 창에서 볼 수 있음

    # return render(request, 'members/login.html')

    # print(f'{username}, {password}')

    # 인증에 성공하면 posts:post-list로 이동
    # 실패하면 다시 members:login으로 이동
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('posts:post-list')
        else:
            return redirect('members:members-login')
    else:
        return render(request, 'members/login.html')

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('members:members-login')

app/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from posts.models import Post

# posts.url에서 지정
# config.urls에서는 path('posts/', include('posts.urls'))

# post_list(request)
# -> '/posts/' 식으로

# post_detail(request, pk) <- view parameter 및 path 패턴명에 'pk' 사용
# -> '/posts/3/'

# base.html 기준으로
# TEMPLATE 설정 쓸 것 (templates 폴더를 DIRS에 추가)
# 경로이름은 TEMPLATES_DIR로 settings.py의 윗부분에 추가

# post_list는 'posts/post_list.html'
# post_detail은 'posts/post_detail.html' 사용

# 1. view와 url의 연결 구현
# 2. view에서 template을 렌더링하는 기능 추가
# 3. template에서 QuerySet 또는 object를 사용해서 객체 출력
# 4. template에 extend 사용


# '/'에 접근했을 때 post_list URL로 이동시키는 내용 추가 (root URL 접근시자동으로)
# redirect 또는 HttpResponseRedirect 사용
# 1. '/'에 접근했을때 쓸 URL 지정
# 2. '/'에 접근했을때 쓸 view 구현 (def index)
# 3. index view는 post_list로 redirect 시켜주는 기능을 함

def post_list(request):
    # response = 'this is post_list'
    # return render(request, 'posts/post_list.html', context)
    # return HttpResponse('Post List') (시험 1단계)
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'posts/post_list.html', context)


def post_detail(request, pk):
    # response = 'this is post_detail of'
    # return render(request, 'posts/post_detail.html', response % pk)
    # return HttpResponse(f'Post Detail{pk}') (시험 1단계)
    post = Post.objects.get(pk=pk)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Instagram</title>
</head>
<body>

<div>
    <h1>Instagram</h1>
    <!--
    user가 인증되어있으면 '로그아웃하기'라는 링크를 보여주고
    아니면 '로그인하기' 링크 보여주기

    logout_view 만들기
        request.method가 POST일 경우,
        request.user를 로그아웃시킴

        URL : /members/logout/
        view : members.views.logout_view
        로그아웃 완료 후에는 로그인 페이지로 redirect하기
    -->
    <div>
        {% if user.is_authenticated %}
        <!-- <a> 태그로는 POST 요청을 보낼 수 없으므로 form을 써야함 -->
        <form action="{% url 'members:members-logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">로그아웃하기</button>
            </form>
        <!-- <a href="{% url 'members:members-logout' %}">로그아웃하기</a> -->
        {% else %}
        <a href="{% url 'members:members-login' %}">로그인</a>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

app/templates/members/login.html
{% extends 'base.html' %}

{% block content %}

<h1>login_view</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input type="text" title="ID" name="username">
    <input type="text" title="PW" name="password">
    <button type="submit">로그인</button>
</form>

{% endblock %}

app/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>post_detail</h1>

<div>{{ post }}</div>

{% endblock %}

app/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Post_list</h1>
{% for post in posts %}
<!--
post의 author.username과
post.photo를 출력
-->

<div>
    <div>{{post.author.username}}</div>
    <div>{{post.photo}}</div>
    <img width="100%" src="{{ post.photo.url }}" alt="">

    <!-- src = "/media/{{ post.photo.url }}" (하드코딩)
     동일한 내용이지만 자동추적되도록 다시 코딩// src = "{{ post.photo.url }}" -->


</div>
{% endfor %}
{% endblock %}